apiVersion: apps/v1
kind: Deployment
metadata:
  name: reacapp
  labels:
    app: reacapp
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: reacapp
  template:
    metadata:
      labels:
        app: reacapp
    spec:
      containers:
        - name: reacapp-container  # Corrected container name
          image: 381492230049.dkr.ecr.us-east-1.amazonaws.com/pocproject/reacapp:latest  # Public ECR image URL
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SECRET_WORD
              valueFrom:
                secretKeyRef:
                  name: secret-word
                  key: SECRET_WORD
