apiVersion: v1
kind: Service
metadata:
  name: reacservice
  labels:
    app: reacapp
spec:
  type: LoadBalancer
  selector:
    app: reacapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

