apiVersion: v1
kind: Service
metadata:
  name: rearcservice
  labels:
    app: rearcapp
spec:
  type: LoadBalancer
  selector:
    app: rearcapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Updated to match your application's port

