name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker build -f Dockerfile -t my-image-name:latest .

    - name: Download Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-image-name:latest
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'
      continue-on-error: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381492230049.dkr.ecr.us-east-1.amazonaws.com

    - name: Tag the Docker image
      run: docker tag my-image-name:latest 381492230049.dkr.ecr.us-east-1.amazonaws.com/pocproject/reacapp:latest

    - name: Push the Docker image to Amazon ECR
      run: docker push 381492230049.dkr.ecr.us-east-1.amazonaws.com/pocproject/reacapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Verify kubectl Installation
      run: kubectl version --client

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name pocproject_Cluster

    - name: Verify Kubernetes Context
      run: kubectl config current-context

    - name: Wait for kubeconfig to propagate
      run: sleep 10

    - name: Update image in Kubernetes manifest
      run: |
        sed -i 's|image:.*|image: 381492230049.dkr.ecr.us-east-1.amazonaws.com/pocproject/reacapp:latest|' k8s/kubernetes-deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply --validate=false -f k8s/kubernetes-deployment.yaml
        kubectl apply --validate=false -f k8s/service.yaml
